### ISSUE TITLE
Feature Request:  Find/Replace with regex

### ISSUE THREAD

**Issue by rjshaver** [alexd/metapad#7]
I have been looking at a way to do a regex search/replace in metapad and have not gotten it to work.  I hope I am not bringing up an old subject or have missed a built in feature.  It looks like you have been the primary and sole programmer on this project.  I really like the interface and how quick it works to perform text manipulation.  I am really tired of MS's notepad and how slow and unresponsive it is.  Thank you for your hard work.  
Would you be interested in putting in this feature?  Or would you be willing for anyone to make changes to input the original project?  Or do you even have time to put into this?  Thanks again.  Sincerely, Randy

**Comment by sobitcorp** [comment]
While it's not true regex, wildcards are supported now in upstream v3.7

https://github.com/sobitcorp/metapad

**Comment by rjshaver** [comment]
Thanks for the work.
